In [5]:
%load_ext autoreload
%autoreload 2
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root
import h5py
import os
import itertools
from scipy.special import kn
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
n_cfgs = 5
n_ops = 5
mat_elems = np.zeros((n_cfgs, n_ops), dtype = np.float64)
mat_elems_σ = np.zeros((n_cfgs, n_ops), dtype = np.float64)
configs = ['24I/ml_0p01', '24I/ml_0p005', '32I/ml0p008', '32I/ml0p006', '32I/ml0p004']
labels = ['O1', 'O2', 'O3', 'O1p', 'O2p']
for cfg_idx, config in enumerate(configs):
    path = '/Users/theoares/Dropbox (MIT)/research/0nubb/short_distance/fits/' + config + '/fit_params.h5'
    f = h5py.File(path, 'r')
    for op_idx in range(n_ops):
        mat_elems[cfg_idx, op_idx] = f[labels[op_idx] + '/mean'][()]
        mat_elems_σ[cfg_idx, op_idx] = f[labels[op_idx] + '/std'][()]
    f.close()

In [4]:
print(mat_elems)
print(mat_elems_σ)

[[-0.04656432 -0.08022133  0.00277413 -0.14389072  0.01957488]
 [-0.03917458 -0.06696432  0.00139919 -0.12275337  0.01639945]
 [-0.01476021 -0.02322309  0.00066709 -0.04590876  0.00577513]
 [-0.01307662 -0.02061964  0.00045255 -0.04093731  0.00514034]
 [-0.01174265 -0.01839895  0.00027605 -0.0370198   0.00459215]]
[[2.84985786e-04 6.46432297e-04 1.34095153e-05 8.99060425e-04
  1.57551502e-04]
 [2.41377164e-04 6.95264040e-04 1.05219362e-05 7.57158809e-04
  1.72235492e-04]
 [1.07282476e-04 2.14839087e-04 4.39944448e-06 3.40621166e-04
  5.44631817e-05]
 [9.07497750e-05 2.02615319e-04 2.85400038e-06 2.91981055e-04
  5.04492862e-05]
 [7.88810704e-05 2.02793588e-04 1.85466329e-06 2.53055916e-04
  5.04578252e-05]]


In [10]:
def f0(m, L):
    f0 = 0
    for n1, n2, n3 in itertools.product(range(L), repeat = 3):
        if n1 == 0 and n2 == 0 and n3 == 0:
            continue
        n = np.sqrt(float(n1) ** 2 + float(n2) ** 2 + float(n3) ** 2)
        f0 += -2 * kn(0, m * L * n)
    return f0
def f1(m, L):
    f1 = 0
    for n1, n2, n3 in itertools.product(range(L), repeat = 3):
        if n1 == 0 and n2 == 0 and n3 == 0:
            continue
        n = np.sqrt(float(n1) ** 2 + float(n2) ** 2 + float(n3) ** 2)
        f1 += 4 * kn(1, m * L * n) / (m * L * n)
    return f0